#!/bin/bash
# Automated reproduction script for Persistent Stochastic Ablation study
# Generated by generate_reproduction_tests.py

set -e  # Exit on any error
echo 'Starting reproduction tests...'

echo 'Testing architecture: [1*2048]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*2048]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x2048_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*2048]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x2048_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*2048]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x2048_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*2048]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x2048_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*1024]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*1024]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x1024_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*1024]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x1024_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*1024]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x1024_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*1024]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x1024_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*512]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*512]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x512_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*512]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x512_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*512]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x512_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*512]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x512_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*256]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*256]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x256_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*256]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x256_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*256]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x256_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*256]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x256_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*128]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*128]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x128_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*128]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x128_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*128]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x128_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*128]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x128_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*64]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*64]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x64_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*64]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x64_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*64]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x64_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*64]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x64_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*32]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*32]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x32_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*32]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x32_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*32]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x32_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*32]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x32_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*16]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*16]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x16_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*16]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x16_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*16]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x16_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*16]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x16_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*8]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*8]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x8_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*8]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x8_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*8]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x8_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*8]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x8_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*4]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*4]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x4_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*4]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x4_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*4]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x4_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*4]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x4_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*939]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*939]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x939_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*939]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x939_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*939]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x939_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*939]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x939_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*588]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*588]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x588_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*588]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x588_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*588]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x588_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*588]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x588_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*354]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*354]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x354_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*354]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x354_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*354]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x354_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*354]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x354_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*214]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*214]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x214_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*214]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x214_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*214]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x214_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*214]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x214_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*115]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*115]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x115_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*115]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x115_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*115]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x115_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*115]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x115_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*59]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*59]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x59_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*59]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x59_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*59]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x59_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*59]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x59_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*30]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*30]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x30_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*30]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x30_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*30]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x30_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*30]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x30_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*16]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*16]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x16_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*16]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x16_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*16]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x16_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*16]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x16_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*8]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*8]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x8_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*8]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x8_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*8]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x8_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*8]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x8_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*4]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*4]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x4_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*4]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x4_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*4]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x4_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*4]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x4_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [115*115]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[115*115]" --ablation-mode none --meta-loops 100 --model-dir "./models/115x115_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[115*115]" --ablation-mode full --meta-loops 100 --model-dir "./models/115x115_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[115*115]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/115x115_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[115*115]" --ablation-mode output --meta-loops 100 --model-dir "./models/115x115_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [91*91]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[91*91]" --ablation-mode none --meta-loops 100 --model-dir "./models/91x91_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[91*91]" --ablation-mode full --meta-loops 100 --model-dir "./models/91x91_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[91*91]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/91x91_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[91*91]" --ablation-mode output --meta-loops 100 --model-dir "./models/91x91_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [71*71]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[71*71]" --ablation-mode none --meta-loops 100 --model-dir "./models/71x71_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[71*71]" --ablation-mode full --meta-loops 100 --model-dir "./models/71x71_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[71*71]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/71x71_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[71*71]" --ablation-mode output --meta-loops 100 --model-dir "./models/71x71_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [56*56]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[56*56]" --ablation-mode none --meta-loops 100 --model-dir "./models/56x56_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[56*56]" --ablation-mode full --meta-loops 100 --model-dir "./models/56x56_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[56*56]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/56x56_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[56*56]" --ablation-mode output --meta-loops 100 --model-dir "./models/56x56_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [44*44]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[44*44]" --ablation-mode none --meta-loops 100 --model-dir "./models/44x44_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[44*44]" --ablation-mode full --meta-loops 100 --model-dir "./models/44x44_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[44*44]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/44x44_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[44*44]" --ablation-mode output --meta-loops 100 --model-dir "./models/44x44_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [35*35]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[35*35]" --ablation-mode none --meta-loops 100 --model-dir "./models/35x35_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[35*35]" --ablation-mode full --meta-loops 100 --model-dir "./models/35x35_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[35*35]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/35x35_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[35*35]" --ablation-mode output --meta-loops 100 --model-dir "./models/35x35_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [26*26]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[26*26]" --ablation-mode none --meta-loops 100 --model-dir "./models/26x26_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[26*26]" --ablation-mode full --meta-loops 100 --model-dir "./models/26x26_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[26*26]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/26x26_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[26*26]" --ablation-mode output --meta-loops 100 --model-dir "./models/26x26_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [18*18]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[18*18]" --ablation-mode none --meta-loops 100 --model-dir "./models/18x18_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[18*18]" --ablation-mode full --meta-loops 100 --model-dir "./models/18x18_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[18*18]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/18x18_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[18*18]" --ablation-mode output --meta-loops 100 --model-dir "./models/18x18_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [12*12]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[12*12]" --ablation-mode none --meta-loops 100 --model-dir "./models/12x12_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[12*12]" --ablation-mode full --meta-loops 100 --model-dir "./models/12x12_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[12*12]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/12x12_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[12*12]" --ablation-mode output --meta-loops 100 --model-dir "./models/12x12_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [8*8]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[8*8]" --ablation-mode none --meta-loops 100 --model-dir "./models/8x8_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[8*8]" --ablation-mode full --meta-loops 100 --model-dir "./models/8x8_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[8*8]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/8x8_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[8*8]" --ablation-mode output --meta-loops 100 --model-dir "./models/8x8_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [7*7]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[7*7]" --ablation-mode none --meta-loops 100 --model-dir "./models/7x7_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[7*7]" --ablation-mode full --meta-loops 100 --model-dir "./models/7x7_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[7*7]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/7x7_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[7*7]" --ablation-mode output --meta-loops 100 --model-dir "./models/7x7_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [6*6]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[6*6]" --ablation-mode none --meta-loops 100 --model-dir "./models/6x6_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[6*6]" --ablation-mode full --meta-loops 100 --model-dir "./models/6x6_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[6*6]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/6x6_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[6*6]" --ablation-mode output --meta-loops 100 --model-dir "./models/6x6_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [5*5]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[5*5]" --ablation-mode none --meta-loops 100 --model-dir "./models/5x5_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[5*5]" --ablation-mode full --meta-loops 100 --model-dir "./models/5x5_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[5*5]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/5x5_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[5*5]" --ablation-mode output --meta-loops 100 --model-dir "./models/5x5_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [4*4]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[4*4]" --ablation-mode none --meta-loops 100 --model-dir "./models/4x4_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[4*4]" --ablation-mode full --meta-loops 100 --model-dir "./models/4x4_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[4*4]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/4x4_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[4*4]" --ablation-mode output --meta-loops 100 --model-dir "./models/4x4_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [3*3]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[3*3]" --ablation-mode none --meta-loops 100 --model-dir "./models/3x3_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[3*3]" --ablation-mode full --meta-loops 100 --model-dir "./models/3x3_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[3*3]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/3x3_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[3*3]" --ablation-mode output --meta-loops 100 --model-dir "./models/3x3_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/1x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/1x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/1x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [939*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[939*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/939x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[939*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/939x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[939*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/939x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[939*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/939x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [588*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[588*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/588x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[588*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/588x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[588*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/588x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[588*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/588x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [354*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[354*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/354x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[354*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/354x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[354*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/354x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[354*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/354x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [214*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[214*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/214x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[214*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/214x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[214*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/214x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[214*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/214x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [115*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[115*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/115x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[115*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/115x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[115*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/115x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[115*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/115x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [59*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[59*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/59x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[59*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/59x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[59*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/59x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[59*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/59x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [30*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[30*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/30x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[30*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/30x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[30*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/30x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[30*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/30x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [16*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[16*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/16x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[16*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/16x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[16*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/16x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[16*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/16x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [8*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[8*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/8x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[8*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/8x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[8*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/8x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[8*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/8x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [4*2]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[4*2]" --ablation-mode none --meta-loops 100 --model-dir "./models/4x2_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[4*2]" --ablation-mode full --meta-loops 100 --model-dir "./models/4x2_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[4*2]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/4x2_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[4*2]" --ablation-mode output --meta-loops 100 --model-dir "./models/4x2_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2048*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2048*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/2048x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2048*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/2048x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2048*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2048x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2048*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/2048x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [1024*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[1024*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/1024x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[1024*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/1024x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[1024*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/1024x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[1024*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/1024x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [512*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[512*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/512x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[512*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/512x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[512*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/512x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[512*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/512x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [256*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[256*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/256x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[256*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/256x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[256*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/256x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[256*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/256x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [128*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[128*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/128x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[128*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/128x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[128*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/128x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[128*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/128x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [64*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[64*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/64x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[64*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/64x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[64*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/64x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[64*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/64x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [32*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[32*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/32x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[32*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/32x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[32*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/32x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[32*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/32x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [16*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[16*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/16x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[16*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/16x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[16*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/16x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[16*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/16x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [8*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[8*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/8x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[8*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/8x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[8*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/8x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[8*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/8x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [4*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[4*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/4x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[4*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/4x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[4*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/4x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[4*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/4x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'Testing architecture: [2*1]'
echo '  Running none ablation mode...'
poetry run train -- --arch "[2*1]" --ablation-mode none --meta-loops 100 --model-dir "./models/2x1_none/" --debug
echo '  Completed'

echo '  Running full ablation mode...'
poetry run train -- --arch "[2*1]" --ablation-mode full --meta-loops 100 --model-dir "./models/2x1_full/" --debug
echo '  Completed'

echo '  Running hidden ablation mode...'
poetry run train -- --arch "[2*1]" --ablation-mode hidden --meta-loops 100 --model-dir "./models/2x1_hidden/" --debug
echo '  Completed'

echo '  Running output ablation mode...'
poetry run train -- --arch "[2*1]" --ablation-mode output --meta-loops 100 --model-dir "./models/2x1_output/" --debug
echo '  Completed'

echo 'Architecture completed'

echo 'All reproduction tests completed!'
